version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres@localhost:5432/slack_de_step_test"

      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: slack_de_step_test

      - image: redis

    working_directory: ~/slack-de-step
    environment:
      TZ: "Asia/Tokyo"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run: gem install bundler

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle --clean

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Update Chromedriver
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get --only-upgrade install google-chrome-stable

      - restore_cache:
          keys:
            - rails-yarn-{{ checksum "yarn.lock" }}
            - rails-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: rails-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: rubocop
          command: bundle exec rubocop -c .rubocop.yml -A

      - run:
          name: db migration
          command: bundle exec rails db:schema:load

      - run:
          name: System Test
          command: bundle exec rspec spec/system

      - run:
          name: Model Test
          command: bundle exec rspec spec/models

      - run:
          name: Request Test
          command: bundle exec rspec spec/requests

      - run:
          name: save screenshots
          command: |
            echo "my artifact file" > /slack-de-step/artifact-1;
            mkdir /slack-de-step/artifacts;
            echo "my artifact files in a dir" > /slack-de-step/artifacts/artifact-2;

      - store_artifacts:
          path: /slack-de-step/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: slack-de-step/artifacts/

workflows:
  version: 2

  workflow:
    jobs:
      - build
