version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: "postgres://postgres@localhost:5432/slack_de_step_test"

      - image: circleci/postgres:10.3-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: slack_de_step_test

      - image: redis

    working_directory: ~/slack-de-step
    environment:
      TZ: "Asia/Tokyo"

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run: gem install bundler

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle --clean

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: update & exec Chromedriver
          command: |
            CHROME_VERSION=$(google-chrome --version | sed -r 's/[^0-9]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/g')
               CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
               bundle exec chromedriver-update $CHROMEDRIVER_VERSION
               chromedriver
          background: true

      - restore_cache:
          keys:
            - rails-yarn-{{ checksum "yarn.lock" }}
            - rails-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: rails-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: rubocop
          command: bundle exec rubocop -c .rubocop.yml -a

      - run:
          name: db migration
          command: bundle exec rails db:schema:load

      - run:
          name: Install Japanese font
          command: sudo apt-get install fonts-migmix

      - run:
          name: System Test
          command: bundle exec rspec spec/system

      - run:
          name: Model Test
          command: bundle exec rspec spec/models

      - run:
          name: Request Test
          command: bundle exec rspec spec/requests

workflows:
  version: 2

  workflow:
    jobs:
      - build
